version: "3"
services:
  api:
    build:
      context: .
      dockerfile: .docker/server.dockerfile
    command: poetry run uvicorn core.asgi:app --host 0.0.0.0
    # command: python -m http.server
    volumes:
      - ./:/server
    ports:
      - "8000:8000"
